#!/bin/bash
#SBATCH --job-name=darus_ensemble
#SBATCH --output=logs/slurm/%x_%A_%a.out
#SBATCH --error=logs/slurm/%x_%A_%a.err
#SBATCH --time=02:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=16G
#SBATCH --gres=gpu:1
#SBATCH --partition=gpu
# Train all 5 ensemble members in parallel as a job array.
# Submit with: sbatch --array=0-4 scripts/slurm/train_ensemble.sh
#SBATCH --array=0-4

# ── Environment ────────────────────────────────────────────────────────────────
source venv/bin/activate
export PYTHONPATH="$(pwd):${PYTHONPATH}"

# ── Per-member config ──────────────────────────────────────────────────────────
# Each array task trains one member. Configs are generated by train_ensemble.py
# and written to experiments/results/uncertainty/ensemble_lstm/model_{i}/
MEMBER_DIR="experiments/results/uncertainty/ensemble_lstm/model_${SLURM_ARRAY_TASK_ID}"
CONFIG="${MEMBER_DIR}/config.yaml"

echo "Job array: $SLURM_ARRAY_JOB_ID  Task: $SLURM_ARRAY_TASK_ID"
echo "Node: $SLURMD_NODENAME  GPU: $CUDA_VISIBLE_DEVICES"
echo "Member dir: $MEMBER_DIR"
echo "Started: $(date)"

mkdir -p logs/slurm "$MEMBER_DIR"

# Generate the per-member config if it doesn't exist yet
python -u -c "
import yaml, os, shutil
base = yaml.safe_load(open('experiments/configs/uncertainty/p2_lstm_ensemble.yaml'))
member_dir = '${MEMBER_DIR}'
os.makedirs(member_dir, exist_ok=True)
base['logging'] = {'save_dir': member_dir, 'run_name': '.'}
# Use array task ID as seed offset (train_baseline reads config_dir for ckpt path)
out = os.path.join(member_dir, 'config.yaml')
yaml.dump(base, open(out, 'w'), default_flow_style=False)
print(f'Wrote {out}')
"

python -u -m src.training.train_baseline --config "$CONFIG"

echo "Finished member $SLURM_ARRAY_TASK_ID: $(date)"
