"""Generate manuscript tables and figures from structured results only.

    python -m src.analysis.report --rules experiments/configs/v3/analysis_rules.yaml

Every number comes from the bootstrap outputs, metrics.json files or saved
predictions named in the frozen rules file; nothing is typed by hand. The run
fails (no partial output) if any evaluation listed in the eval list, any
bootstrap summary, or any required repeat is missing. An analysis manifest
records the SHA-256 of every input and output.

Outputs in <out_dir>/: tables/*.csv + *.tex, figures/*.pdf, analysis_manifest.json.
"""

import argparse
import csv
import glob
import hashlib
import json
import os

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402
import yaml  # noqa: E402

from src.analysis.rebuild import EvalDir  # noqa: E402


def sha(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()


class Inputs:
    def __init__(self, rules):
        self.r = rules
        self.used = []
        self.missing = []

    def path(self, p, required=True):
        if os.path.exists(p):
            self.used.append(p)
        elif required:
            self.missing.append(p)
        return p

    def evals(self, pattern):
        return sorted(glob.glob(os.path.join(self.r["eval_root"], pattern)))


def check_required(inp, rules):
    with open(rules["eval_list"]) as f:
        for row in csv.DictReader(f, delimiter="\t"):
            inp.path(os.path.join(rules["eval_root"], row["tag"], "metrics.json"))
    for sp in rules["splits"]:
        inp.path(os.path.join(rules["bootstrap_dir"], f"summary_{sp}.csv"))
        inp.path(os.path.join(rules["bootstrap_dir"], f"paired_{sp}.csv"))
    for name, m in rules["uq_methods"].items():
        n = len(inp.evals(m["evals"]))
        if n != rules["repeats"]:
            inp.missing.append(f"{name}: {n} of {rules['repeats']} repeats ({m['evals']})")
    if inp.missing:
        raise FileNotFoundError("required inputs missing; no output written:\n  " + "\n  ".join(inp.missing))


def fmt(est, lo, hi, pct=False, nd=3):
    if pct:
        return f"{100 * est:.1f} [{100 * lo:.1f}, {100 * hi:.1f}]"
    return f"{est:.{nd}g} [{lo:.{nd}g}, {hi:.{nd}g}]"


def write_table(df, stem, out, caption):
    os.makedirs(os.path.join(out, "tables"), exist_ok=True)
    df.to_csv(os.path.join(out, "tables", f"{stem}.csv"), index=False)
    tex = df.to_latex(index=False, escape=True, caption=caption, label=f"tab:{stem}", column_format="l" * len(df.columns))
    tex = tex.replace("\\toprule", "\\toprule").replace("\\begin{table}", "\\begin{table}[t]\n\\centering\\footnotesize")
    with open(os.path.join(out, "tables", f"{stem}.tex"), "w") as f:
        f.write(f"% generated by src.analysis.report from {os.path.basename(stem)} sources; do not edit\n" + tex)
    return [os.path.join(out, "tables", f"{stem}.{e}") for e in ("csv", "tex")]


def summaries(rules):
    return {sp: pd.read_csv(os.path.join(rules["bootstrap_dir"], f"summary_{sp}.csv")).set_index(["method", "statistic"])
            for sp in rules["splits"]}


def table_baselines(rules, S, out):
    rows = []
    for name, label in rules["baselines"].items():
        row = {"Model": label}
        for sp in rules["splits"]:
            s = S[sp]
            if (name, "rmse_norm_mean") not in s.index:
                raise KeyError(f"{name} missing from bootstrap summary ({sp})")
            e = s.loc[(name, "rmse_norm_mean")]
            row[f"{rules['split_labels'][sp]}: norm. RMSE [95% CI]"] = fmt(e.estimate, e.ci_low, e.ci_high)
            for ch in rules["channels"]:
                row[f"{sp} RMSE {ch} ({rules['units'][ch]})"] = f"{s.loc[(name, f'rmse_{ch}')].estimate:.4g}"
            row[f"{sp} seed SD"] = "" if np.isnan(e.seed_sd) else f"{e.seed_sd:.2g}"
            row["repeats"] = int(e.n_repeats)
        rows.append(row)
    return write_table(pd.DataFrame(rows), "baselines", out,
                       "Point accuracy (generated). Normalised RMSE = mean over channels of RMSE / training-target SD; "
                       "95\\% recording-level bootstrap CI; seed SD across repeats.")


def table_uq(rules, S, out):
    lvl = int(round(100 * rules["primary"]["level"]))
    rows = []
    for name, m in rules["uq_methods"].items():
        for sp in rules["splits"]:
            s = S[sp]
            c, w, i = (s.loc[(name, k)] for k in ("coverage", "width_norm_mean", "iscore_norm_mean"))
            rows.append({"Method": m["label"], "Split": rules["split_labels"][sp],
                         f"Coverage % (nominal {lvl}) [95% CI]": fmt(c.estimate, c.ci_low, c.ci_high, pct=True),
                         "Norm. width [95% CI]": fmt(w.estimate, w.ci_low, w.ci_high),
                         "Norm. interval score [95% CI]": fmt(i.estimate, i.ci_low, i.ci_high),
                         "Coverage seed SD (pp)": "" if np.isnan(c.seed_sd) else f"{100 * c.seed_sd:.1f}",
                         "Recordings": int(c.n_recordings)})
    return write_table(pd.DataFrame(rows), "uq_summary", out,
                       f"Interval quality at the primary nominal level {lvl}\\% (generated). Marginal coverage of scalar "
                       "predictions; widths and interval scores normalised by training-target SD.")


def table_channels(rules, S, out):
    rows = []
    for name, m in rules["uq_methods"].items():
        for sp in rules["splits"]:
            row = {"Method": m["label"], "Split": rules["split_labels"][sp]}
            for ch in rules["channels"]:
                c = S[sp].loc[(name, f"coverage_{ch}")]
                w = S[sp].loc[(name, f"width_{ch}")]
                row[f"cov {ch} %"] = f"{100 * c.estimate:.1f} [{100 * c.ci_low:.1f}, {100 * c.ci_high:.1f}]"
                row[f"width {ch} ({rules['units'][ch]})"] = f"{w.estimate:.3g}"
            rows.append(row)
    return write_table(pd.DataFrame(rows), "uq_channels", out,
                       "Per-channel coverage (95\\% CI) and mean width in physical units (generated).")


def table_paired(rules, out):
    frames = []
    for sp in rules["splits"]:
        p = pd.read_csv(os.path.join(rules["bootstrap_dir"], f"paired_{sp}.csv"))
        p = p[p.statistic.isin(rules["paired_statistics"])]
        frames.append(p.assign(split=rules["split_labels"][sp]))
    df = pd.concat(frames)
    df["difference [95% CI]"] = [fmt(r.difference, r.ci_low, r.ci_high) for r in df.itertuples()]
    df = df[["split", "method_a", "method_b", "statistic", "difference [95% CI]", "share_draws_positive", "n_recordings"]]
    return write_table(df, "paired_differences", out,
                       "Paired differences A$-$B on identical recordings (generated; recording-level bootstrap). "
                       "Descriptive; no multiplicity-adjusted significance claims.")


def figure_levels(rules, out):
    fig, axes = plt.subplots(1, len(rules["splits"]), figsize=(5 * len(rules["splits"]), 4), sharey=True)
    axes = np.atleast_1d(axes)
    levels = rules["levels"]
    for ax, sp in zip(axes, rules["splits"]):
        ax.plot(levels, levels, "k:", lw=1, label="nominal")
        for name, m in rules["uq_methods"].items():
            variant = rules["primary"]["variant"] if m["variant"] == "primary" else m["variant"]
            covs = []
            for d in glob.glob(os.path.join(rules["eval_root"], m["evals"])):
                ed = EvalDir(d)
                covs.append([ed.stored(sp, m["method"] if m["method"] != "point" else "conformal", variant, l)["coverage"]
                             for l in levels])
            covs = np.array(covs)
            ax.errorbar(levels, covs.mean(0), yerr=[covs.mean(0) - covs.min(0), covs.max(0) - covs.mean(0)],
                        marker="o", ms=3, lw=1, capsize=2, label=m["label"])
        ax.set_title(rules["split_labels"][sp])
        ax.set_xlabel("Nominal level")
        ax.grid(alpha=0.3)
    axes[0].set_ylabel("Empirical marginal coverage (mean, min–max over repeats)")
    axes[-1].legend(fontsize=6, loc="lower right")
    fig.tight_layout()
    p = os.path.join(out, "figures", "coverage_vs_level.pdf")
    fig.savefig(p)
    plt.close(fig)
    return [p]


def figure_horizon(rules, out):
    lvl, var = rules["primary"]["level"], rules["primary"]["variant"]
    fig, axes = plt.subplots(2, len(rules["splits"]), figsize=(5 * len(rules["splits"]), 6), sharex=True)
    axes = np.array(axes).reshape(2, -1)
    for j, sp in enumerate(rules["splits"]):
        for name, m in rules["uq_methods"].items():
            if m["variant"] != "primary":
                continue
            cov, wid = [], []
            for d in glob.glob(os.path.join(rules["eval_root"], m["evals"])):
                ed = EvalDir(d)
                iv = ed.stored(sp, m["method"] if m["method"] != "point" else "conformal", var, lvl)
                cov.append(iv["coverage_horizon"])
                wid.append((np.asarray(iv["width_horizon_channel"]) / ed.scale).mean(axis=1))
            steps = np.arange(1, len(cov[0]) + 1)
            axes[0, j].plot(steps, np.mean(cov, 0), lw=1, label=m["label"])
            axes[1, j].plot(steps, np.mean(wid, 0), lw=1, label=m["label"])
        axes[0, j].axhline(lvl, color="k", ls=":", lw=1)
        axes[0, j].set_title(rules["split_labels"][sp])
        axes[1, j].set_xlabel("Forecast step (s)")
    axes[0, 0].set_ylabel("Coverage by step")
    axes[1, 0].set_ylabel("Mean normalised width")
    axes[0, -1].legend(fontsize=6)
    fig.tight_layout()
    p = os.path.join(out, "figures", "horizon_resolved.pdf")
    fig.savefig(p)
    plt.close(fig)
    return [p]


def select_example_window(ed, split):
    """Frozen rule: median of per-window mean-over-channels RMSE/scale; ties -> smallest window_id."""
    a = ed.arrays(split)
    per_window = (np.sqrt(((a["mean"] - a["y"]) ** 2).mean(axis=1)) / ed.scale).mean(axis=1)
    med = np.median(per_window)
    dist = np.abs(per_window - med)
    return int(np.flatnonzero(dist == dist.min())[0])


def figure_example(rules, out, data_base="data/processed/darus"):
    ex = rules["example_figure"]
    ref = EvalDir(os.path.join(rules["eval_root"], ex["reference_eval"]))
    wid = select_example_window(ref, ex["split"])
    win = ref.windows(ex["split"]).iloc[wid]
    split_dir = {"test": "patrol_ship_routine/test", "ood_test": "patrol_ship_ood/test"}[ex["split"]]
    rec = pd.read_csv(os.path.join(data_base, split_dir, win.recording))
    H = ex["history_steps"]
    start = int(win.start_row)
    chans = rules["channels"]
    fig, axes = plt.subplots(len(chans), len(ex["panels"]), figsize=(3.2 * len(ex["panels"]), 1.6 * len(chans)),
                             sharex=True, sharey="row", squeeze=False)
    for j, panel in enumerate(ex["panels"]):
        ed = EvalDir(os.path.join(rules["eval_root"], panel["eval"]))
        if not ed.windows(ex["split"]).equals(ref.windows(ex["split"])):
            raise ValueError(f"{panel['eval']}: windows differ from the reference evaluation")
        iv = ed.interval(ex["split"], panel["kind"], rules["primary"]["variant"], rules["primary"]["level"])
        a = ed.arrays(ex["split"])
        for i, ch in enumerate(chans):
            ax = axes[i, j]
            ax.plot(np.arange(-H + 1, 1), rec[ch].to_numpy()[start:start + H], color="0.4", lw=1, label="history")
            t = np.arange(1, a["y"].shape[1] + 1)
            ax.fill_between(t, iv.lower[wid, :, i], iv.upper[wid, :, i], alpha=0.3, lw=0, label="interval")
            ax.plot(t, a["y"][wid, :, i], "k--", lw=1, label="observed")
            ax.plot(t, a["mean"][wid, :, i], lw=1, label="prediction")
            if j == 0:
                ax.set_ylabel(f"{ch} ({rules['units'][ch]})", fontsize=7)
            if i == 0:
                ax.set_title(panel["label"], fontsize=7)
            ax.tick_params(labelsize=6)
    h, l = axes[0, 0].get_legend_handles_labels()
    fig.legend(h, l, loc="lower center", ncol=4, fontsize=7, frameon=False)
    fig.suptitle(f"{rules['split_labels'][ex['split']]} window {wid} ({win.recording}, start row {start}); "
                 f"{int(100 * rules['primary']['level'])}% {rules['primary']['variant']} intervals", fontsize=7)
    fig.tight_layout(rect=(0, 0.04, 1, 1))
    p = os.path.join(out, "figures", "example_window.pdf")
    fig.savefig(p)
    plt.close(fig)
    return [p], {"window_id": wid, "recording": win.recording, "start_row": start, "rule": ex["rule"]}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rules", required=True)
    ap.add_argument("--data_base", default="data/processed/darus")
    args = ap.parse_args()
    rules = yaml.safe_load(open(args.rules))
    inp = Inputs(rules)
    check_required(inp, rules)
    out = rules["out_dir"]
    os.makedirs(os.path.join(out, "figures"), exist_ok=True)

    S = summaries(rules)
    outputs = []
    outputs += table_baselines(rules, S, out)
    outputs += table_uq(rules, S, out)
    outputs += table_channels(rules, S, out)
    outputs += table_paired(rules, out)
    outputs += figure_levels(rules, out)
    outputs += figure_horizon(rules, out)
    ex_paths, example = figure_example(rules, out, args.data_base)
    outputs += ex_paths

    manifest = {"rules": args.rules, "rules_sha256": sha(args.rules), "rules_version": rules["version"],
                "inputs": {p: sha(p) for p in sorted(set(inp.used))},
                "outputs": {p: sha(p) for p in outputs}, "example_window": example}
    with open(os.path.join(out, "analysis_manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)
    print(f"wrote {len(outputs)} outputs to {out}")


if __name__ == "__main__":
    main()
