"""Publication presentation layer for the v3 benchmark (tables + figures).

    python -m src.analysis.report_pub --out experiments/analysis/v3/report_pub

Reads ONLY frozen outputs (bootstrap summaries/paired files, stored metrics,
post-hoc CSVs, executed configs); it never recomputes intervals or scores.
Differences from the frozen `report.py` output are presentation only and are
logged in REVISION_TRACKER.md (deviation D-P1):
  * precise construction names (AR-/EN-/DN-/GN-SCP, raw bands),
  * compact LaTeX tables with the CI estimand stated in every caption,
  * the ridge/naive rows of the frozen bootstrap spec included in the UQ tables,
  * figures with an uncrowded legend (colour = construction, line = backbone),
  * post-hoc tables clearly labelled as such.
The example-window rule and all data are unchanged.
"""

import argparse
import glob
import hashlib
import json
import os

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402
import yaml  # noqa: E402

from src.analysis import report as frozen  # noqa: E402

BOOT = "experiments/analysis/v3/bootstrap"
METRICS = "experiments/manifests/stageC_2026-09-28/metrics"
POSTHOC = "experiments/analysis/v3/posthoc"
CH = ["u", "v", "p", "r", "phi"]
CHTEX = {"u": "$u$", "v": "$v$", "p": "$p$", "r": "$r$", "phi": "$\\phi$"}
UNITS = {"u": "m\\,s$^{-1}$", "v": "m\\,s$^{-1}$", "p": "rad\\,s$^{-1}$", "r": "rad\\,s$^{-1}$", "phi": "rad"}

# bootstrap method -> (short label, family, backbone); order = table order
ROWS = [
    ("conformal_lstm", "AR-SCP", "AR", "LSTM"), ("conformal_gru", "AR-SCP", "AR", "GRU"),
    ("conformal_tcn", "AR-SCP", "AR", "TCN"), ("conformal_mlp", "AR-SCP", "AR", "MLP"),
    ("conformal_linear", "AR-SCP", "AR", "Linear (SGD)"), ("conformal_ridge", "AR-SCP", "AR", "Ridge"),
    ("conformal_naive", "AR-SCP", "AR", "Naive"),
    ("ensemble_lstm", "EN-SCP", "EN", "LSTM"), ("ensemble_mlp", "EN-SCP", "EN", "MLP"),
    ("mcd_lstm", "DN-SCP", "DN", "LSTM"), ("mcd_mlp", "DN-SCP", "DN", "MLP"),
    ("gaussian_lstm", "GN-SCP", "GN", "LSTM"), ("gaussian_mlp", "GN-SCP", "GN", "MLP"),
    ("ensemble_lstm_raw", "Ensemble raw", "ENraw", "LSTM"), ("ensemble_mlp_raw", "Ensemble raw", "ENraw", "MLP"),
    ("mcd_lstm_raw", "Dropout raw", "DNraw", "LSTM"), ("mcd_mlp_raw", "Dropout raw", "DNraw", "MLP"),
    ("gaussian_lstm_raw", "Gaussian raw", "GNraw", "LSTM"), ("gaussian_mlp_raw", "Gaussian raw", "GNraw", "MLP"),
]
# Okabe-Ito colour-blind-safe palette
COLOR = {"AR": "#0072B2", "EN": "#D55E00", "DN": "#E69F00", "GN": "#009E73",
         "ENraw": "#D55E00", "DNraw": "#E69F00", "GNraw": "#009E73"}
LS = {"LSTM": "-", "MLP": "--"}
BASELINES = [("conformal_lstm", "LSTM seq2seq", "lstm"), ("conformal_gru", "GRU seq2seq", "gru"),
             ("conformal_tcn", "TCN", "tcn"), ("conformal_mlp", "MLP", "mlp"),
             ("conformal_linear", "Linear (SGD)", "linear"), ("conformal_ridge", "Linear (ridge, closed form)", "linear"),
             ("conformal_naive", "Naive (last value)", "naive")]
EVAL_TAG = {"conformal_lstm": "lstm_single_rep*", "conformal_mlp": "mlp_single_rep*", "conformal_gru": "gru_rep*",
            "conformal_tcn": "tcn_rep*", "conformal_linear": "linear_rep*", "conformal_ridge": "ridge",
            "conformal_naive": "naive"}


def sha(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()


def signed(x, nd):
    """Format x with nd decimals, adding decimals (up to 4) so that a non-zero value never prints as 0 or -0."""
    for d in range(nd, 5):
        t = f"{x:.{d}f}"
        if float(t) != 0.0 or x == 0.0:
            return t
    return f"{x:.2e}"


def ci_signed(est, lo, hi, scale=1.0, nd=2):
    return f"{signed(scale * est, nd)} [{signed(scale * lo, nd)}, {signed(scale * hi, nd)}]"


def ci(est, lo, hi, scale=1.0, nd=3):
    f = f"{{:.{nd}f}}"
    return f"{f.format(scale * est)} [{f.format(scale * lo)}, {f.format(scale * hi)}]"


def summaries():
    return {sp: pd.read_csv(f"{BOOT}/summary_{sp}.csv").set_index(["method", "statistic"]) for sp in ("test", "ood_test")}


def tex_table(path, caption, label, colspec, header, rows, note=None, size="\\footnotesize"):
    lines = ["% generated by src.analysis.report_pub from frozen v3 outputs; do not edit by hand",
             "\\begin{table*}[tbp]", "\\centering", size, f"\\caption{{{caption}}}", f"\\label{{{label}}}",
             f"\\begin{{tabular}}{{{colspec}}}", "\\toprule", header + " \\\\", "\\midrule"]
    for r in rows:
        is_rule = r.startswith(("\\midrule", "\\cmidrule", "\\addlinespace"))
        lines.append(r if is_rule else r + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    if note:
        lines += [f"\\par\\smallskip\\parbox{{0.95\\textwidth}}{{\\scriptsize {note}}}"]
    lines += ["\\end{table*}"]
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return path


def n_params():
    from src.models.factory import build_model, count_parameters
    out = {}
    for name in ("lstm", "gru", "tcn", "mlp", "linear"):
        cfg = yaml.safe_load(open(f"experiments/configs/v3/{name}.yaml"))
        out[name] = count_parameters(build_model(cfg["model"], 11, 5, 30, 30))
    out["naive"] = 0
    return out


def seed_mean(pattern, fn):
    vals = [fn(json.load(open(p))) for p in sorted(glob.glob(f"{METRICS}/{pattern}.json"))]
    if not vals:
        raise FileNotFoundError(pattern)
    return np.mean(vals, axis=0), len(vals)


def table_roles(out):
    """Data roles from the data audit and the calibration-selection record (no hand-typed counts)."""
    audit = json.load(open("experiments/manifests/data_audit.json"))
    cal = json.load(open("experiments/manifests/calibration_selection.json"))
    n_cal = len(cal[cal["primary"]]["files"])
    per_rec = audit["train"]["valid_windows"] // audit["train"]["n_recordings"]
    rows = [("Fit", audit["train"]["n_recordings"] - n_cal, "gradient updates; scaler fitting"),
            ("Calibration", n_cal, "conformal thresholds; spread floor"),
            ("Validation", audit["val"]["n_recordings"], "checkpoint selection, early stopping, feature decision, ridge penalty"),
            ("ID test", audit["test"]["n_recordings"], "reporting"),
            ("OOD test", audit["ood_test"]["n_recordings"], "reporting (exploratory; consulted in an earlier version)")]
    body = []
    for role, n, use in rows:
        body.append(f"{role} & {n} & {n * per_rec:,} & {use}".replace(",", "{,}", 1) if n * per_rec >= 1000 else f"{role} & {n} & {n * per_rec} & {use}")
    for (role, n, _), (_, sp) in zip(rows[2:], (("val", "val"), ("test", "test"), ("ood", "ood_test"))):
        assert n * per_rec == audit[sp]["valid_windows"], (role, sp)
    lines = ["% generated by src.analysis.report_pub from experiments/manifests; do not edit by hand",
             "\\begin{table}[tbp]", "\\centering\\footnotesize",
             "\\caption{Data roles. Windows: history 30~s, horizon 30~s, stride 1, within recordings ("
             + f"{per_rec:,}".replace(",", "{,}") + " per recording).}",
             "\\label{tab:roles}", "\\begin{tabular}{lrrl}", "\\toprule", "Role & Recordings & Windows & Use \\\\", "\\midrule"]
    lines += [b + " \\\\" for b in body]
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    path = f"{out}/tab_roles.tex"
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return path


def table_baselines(S, out):
    npar = n_params()
    rows = []
    for m, label, key in BASELINES:
        t, o = S["test"].loc[(m, "rmse_norm_mean")], S["ood_test"].loc[(m, "rmse_norm_mean")]
        rows.append(f"{label} & {npar[key]:,} & {int(t.n_repeats)} & {ci(t.estimate, t.ci_low, t.ci_high)} & "
                    f"{ci(o.estimate, o.ci_low, o.ci_high)}")
    cap = ("Deterministic point accuracy (ID test: 30 recordings; OOD test: 29 recordings, exploratory). "
           "Normalised RMSE = mean over the five channels of RMSE divided by the training-target standard deviation of that channel "
           "(dimensionless). Values are means over training repeats; brackets give the 95\\% percentile interval of a cluster bootstrap "
           "that resamples whole recordings (2000 draws) and averages over repeats, i.e.\\ uncertainty due to the finite set of test "
           "recordings, not across-seed variation. Ridge and naive are single deterministic fits.")
    return tex_table(f"{out}/tab_baselines.tex", cap, "tab:baselines", "lrrcc",
                     "Model & Parameters & Repeats & ID normalised RMSE [95\\% CI] & OOD normalised RMSE [95\\% CI]", rows)


def table_channels_rmse(S, out):
    rows = []
    for m, label, _ in BASELINES:
        cells = [f"{S[sp].loc[(m, f'rmse_{c}')].estimate:.4f}" for sp in ("test", "ood_test") for c in CH]
        rows.append(f"{label} & " + " & ".join(cells))
    head = ("Model & " + " & ".join(f"{CHTEX[c]}" for c in CH) + " & " + " & ".join(f"{CHTEX[c]}" for c in CH))
    pre = ("& \\multicolumn{5}{c}{ID test} & \\multicolumn{5}{c}{OOD test (exploratory)} \\\\ "
           "\\cmidrule(lr){2-6}\\cmidrule(lr){7-11}")
    cap = ("Per-channel RMSE in physical units (" + ", ".join(f"{CHTEX[c]}: {UNITS[c]}" for c in CH) +
           "), mean over training repeats; recording-bootstrap intervals for every entry are in the accompanying CSV "
           "(\\texttt{experiments/analysis/v3/bootstrap}). The channels differ by up to two orders of magnitude, so no pooled "
           "error is used for ranking.")
    lines = tex_table(f"{out}/tab_channel_rmse.tex", cap, "tab:channel-rmse", "l" + "r" * 10, pre + "\n" + head, rows)
    return lines


def table_uq(S, out, sp, label):
    rows = ["\\multicolumn{6}{l}{\\emph{Split conformal (calibrated on 9 training recordings excluded from fitting)}}"]
    in_raw = False
    for m, lab, fam, bb in ROWS:
        if fam.endswith("raw") and not in_raw:
            rows += ["\\midrule", "\\multicolumn{6}{l}{\\emph{Uncalibrated bands $\\mu \\pm z_{0.95}\\,s$}}"]
            in_raw = True
        c, w, i = (S[sp].loc[(m, k)] for k in ("coverage", "width_norm_mean", "iscore_norm_mean"))
        sd = "--" if np.isnan(c.seed_sd) else f"{100 * c.seed_sd:.1f}"
        rows.append(f"{lab} & {bb} & {ci(c.estimate, c.ci_low, c.ci_high, 100, 1)} & {ci(w.estimate, w.ci_low, w.ci_high, 1, 2)} & "
                    f"{ci(i.estimate, i.ci_low, i.ci_high, 1, 2)} & {sd}")
    split_name = "ID test (30 recordings)" if sp == "test" else "OOD test (29 recordings; exploratory, see Section~\\ref{sec:limitations})"
    cap = (f"Interval quality at nominal 90\\% on the {split_name}. Coverage = marginal coverage of individual scalar predictions "
           "(all windows, 30 steps, 5 channels); width and interval score (Winkler score, $\\alpha=0.1$) are divided per channel by "
           "the training-target standard deviation and averaged over channels (dimensionless; lower interval score is better). "
           "Brackets: 95\\% recording-level cluster-bootstrap intervals; last column: standard deviation of coverage across the "
           "three training repeats (percentage points), a separate source of variation. AR-SCP rows use the member-0 model of "
           "each repeat (single models); EN-, DN- and GN-SCP use the ensemble mean, dropout mean and Gaussian mean with a score "
           "normalised by the corresponding spread.")
    return tex_table(f"{out}/{label}.tex", cap, f"tab:{label.replace('tab_', '').replace('_', '-')}", "llcccc",
                     "Construction & Backbone & Coverage \\% [95\\% CI] & Norm.\\ width [95\\% CI] & Norm.\\ interval score [95\\% CI] & Seed SD (pp)",
                     rows)


def prose_values(S, out):
    """LaTeX macros for numbers quoted in the running text, computed from the same outputs as the tables."""
    t = S["test"]
    ar_learned = [m for m, _, fam, bb in ROWS if fam == "AR" and bb != "Naive"]
    w = [t.loc[(m, "width_norm_mean")].estimate for m in ar_learned]
    cal = [m for m, _, fam, _ in ROWS if fam in ("AR", "EN", "DN", "GN") and m != "conformal_naive"]
    raw_g = ["gaussian_lstm_raw", "gaussian_mlp_raw"]
    ciw = lambda ms: [100 * (t.loc[(m, "coverage")].ci_high - t.loc[(m, "coverage")].ci_low) for m in ms]
    d = pd.read_csv(f"{POSTHOC}/o1_coverage_breakdown.csv")
    at90 = d[(d.split == "test") & (d.level == 0.9)]
    rng = 100 * (at90.coverage_seed_max - at90.coverage_seed_min)
    raw = at90.construction.str.contains("raw")
    vals = {"ARwidthID": f"{min(w):.2f}--{max(w):.2f}",
            "SeedRangeCal": f"{rng[~raw].max():.1f}", "SeedRangeRawGauss": f"{rng[raw].max():.1f}",
            "CIspanCal": f"{min(ciw(cal)):.1f}--{max(ciw(cal)):.1f}",
            "CIspanRawGauss": "--".join(sorted({f"{x:.1f}" for x in ciw(raw_g)}))}
    path = f"{out}/prose_values.tex"
    with open(path, "w") as f:
        f.write("% generated by src.analysis.report_pub from frozen v3 outputs; do not edit by hand\n")
        f.write("% ARwidthID: ID normalised width, AR-SCP with learned forecasters (excl. naive)\n")
        f.write("% SeedRange*: max range of 90% ID coverage across 3 repeats (pp); CIspan*: width of 95% recording-bootstrap CI (pp)\n")
        for k, v in vals.items():
            f.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
    return path


PAIR_GROUPS = [
    ("Construction vs.\\ AR-SCP on the same backbone (differs in score \\emph{and} predictor)",
     [("ensemble_lstm", "conformal_lstm", "EN-SCP $-$ AR-SCP, LSTM"), ("ensemble_mlp", "conformal_mlp", "EN-SCP $-$ AR-SCP, MLP"),
      ("mcd_lstm", "conformal_lstm", "DN-SCP $-$ AR-SCP, LSTM"), ("mcd_mlp", "conformal_mlp", "DN-SCP $-$ AR-SCP, MLP"),
      ("gaussian_lstm", "conformal_lstm", "GN-SCP $-$ AR-SCP, LSTM"), ("gaussian_mlp", "conformal_mlp", "GN-SCP $-$ AR-SCP, MLP")]),
    ("Backbone (MLP $-$ LSTM) within a construction",
     [("conformal_mlp", "conformal_lstm", "AR-SCP"), ("ensemble_mlp", "ensemble_lstm", "EN-SCP"),
      ("mcd_mlp", "mcd_lstm", "DN-SCP"), ("gaussian_mlp", "gaussian_lstm", "GN-SCP")]),
    ("Calibrated $-$ raw band of the same spread",
     [("ensemble_lstm", "ensemble_lstm_raw", "Ensemble, LSTM"), ("ensemble_mlp", "ensemble_mlp_raw", "Ensemble, MLP"),
      ("mcd_lstm", "mcd_lstm_raw", "Dropout, LSTM"), ("mcd_mlp", "mcd_mlp_raw", "Dropout, MLP"),
      ("gaussian_lstm", "gaussian_lstm_raw", "Gaussian, LSTM"), ("gaussian_mlp", "gaussian_mlp_raw", "Gaussian, MLP")]),
]


def table_paired(out):
    P = {sp: pd.read_csv(f"{BOOT}/paired_{sp}.csv").set_index(["method_a", "method_b", "statistic"]) for sp in ("test", "ood_test")}
    rows = []
    for title, pairs in PAIR_GROUPS:
        rows.append(f"\\multicolumn{{5}}{{l}}{{\\emph{{{title}}}}}")
        for a, b, lab in pairs:
            cells = []
            for sp in ("test", "ood_test"):
                for stat, sc, nd in (("coverage", 100, 1), ("iscore_norm_mean", 1, 2)):  # extra decimals only where needed
                    r = P[sp].loc[(a, b, stat)]
                    cells.append(ci_signed(r.difference, r.ci_low, r.ci_high, sc, nd))
            rows.append(f"{lab} & " + " & ".join(cells))
    pre = ("& \\multicolumn{2}{c}{ID test} & \\multicolumn{2}{c}{OOD test (exploratory)} \\\\ "
           "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}")
    cap = ("Predeclared paired differences (A $-$ B) at nominal 90\\%, computed on identical recordings and windows with shared "
           "bootstrap draws (2000 cluster resamples of recordings; repeats averaged within each draw). $\\Delta$Cov in percentage "
           "points; $\\Delta$IS = difference in normalised interval score (negative = A better). Values are printed with extra decimals where "
           "needed so that no non-zero bound appears as zero. Intervals are descriptive: no "
           "multiplicity adjustment, and an interval that includes zero is not evidence of equivalence.")
    return tex_table(f"{out}/tab_paired.tex", cap, "tab:paired", "lcccc",
                     pre + "\nPair & $\\Delta$Cov (pp) & $\\Delta$IS & $\\Delta$Cov (pp) & $\\Delta$IS", rows)


def table_matched_posthoc(out):
    d = pd.read_csv(f"{POSTHOC}/matched_score_vs_predictor.csv")
    lab = {"spread-normalised": "normalised score on ensemble/dropout/Gaussian mean",
           "abs-residual conformal on": "absolute-residual score on the same mean"}
    rows = []
    fam_name = {"ens": "Ensemble (5 members)", "mcd": "MC dropout (200 passes)", "gauss": "Gaussian head", "single": "Single model (member 0)"}
    for bb in ("LSTM", "MLP"):
        rows.append(f"\\multicolumn{{7}}{{l}}{{\\emph{{{bb} backbone}}}}")
        for fam in ("ens", "mcd", "gauss", "single"):
            sub = d[(d.backbone == bb) & (d.family == fam)]
            for cons in sub.construction.unique():
                if "raw" in cons:
                    continue
                kind = "normalised score" if "spread-normalised" in cons else "absolute-residual score"
                t = sub[(sub.construction == cons) & (sub.split == "test")].iloc[0]
                o = sub[(sub.construction == cons) & (sub.split == "ood_test")].iloc[0]
                rows.append(f"{fam_name[fam]} & {kind} & {100 * t.coverage:.1f} & {t.iscore_norm:.2f} & "
                            f"{100 * o.coverage:.1f} ({'--'.join(f'{100 * float(x):.1f}' for x in o.cov_seed_range.split('-'))}) & "
                            f"{o.width_norm:.2f} & {o.iscore_norm:.2f}")
    cap = ("\\textbf{Post hoc} (not predeclared) matched comparison at nominal 90\\%, from stored evaluation metrics: the same "
           "point predictor with two conformal scores, and the same absolute-residual score with two predictors. Values are means "
           "over three training repeats; the OOD coverage range over repeats is shown in parentheses (percent). Recording-level "
           "intervals were not computed for these contrasts.")
    return tex_table(f"{out}/tab_matched_posthoc.tex", cap, "tab:matched", "llccccc",
                     "\\multicolumn{2}{l}{Predictor / score} & ID cov.\\ (\\%) & ID IS & OOD cov.\\ (\\%) (range) & OOD width & OOD IS", rows)


def table_channel_coverage(S, out):
    rows = []
    for sp, name in (("test", "ID"), ("ood_test", "OOD")):
        rows.append(f"\\multicolumn{{7}}{{l}}{{\\emph{{{name} test}}}}")
        for m, lab, fam, bb in ROWS:
            if fam.endswith("raw") or m in ("conformal_gru", "conformal_tcn", "conformal_linear", "conformal_ridge", "conformal_naive"):
                continue
            cells = [f"{100 * S[sp].loc[(m, f'coverage_{c}')].estimate:.1f}" for c in CH]
            rows.append(f"{lab} & {bb} & " + " & ".join(cells))
    cap = ("Per-channel marginal coverage (\\%) at nominal 90\\%, means over repeats. Recording-bootstrap intervals for each "
           "entry are in the accompanying CSV.")
    return tex_table(f"{out}/tab_channel_coverage.tex", cap, "tab:channel-coverage", "llccccc",
                     "Construction & Backbone & " + " & ".join(CHTEX[c] for c in CH), rows)


def table_o1(out):
    d = pd.read_csv(f"{POSTHOC}/o1_coverage_breakdown.csv")
    d = d[d.split == "test"]
    rows = []
    for cons in d.construction.unique():
        sub = d[d.construction == cons].set_index("level")
        cells = [f"{100 * sub.loc[l].coverage_mean:.1f}" for l in (0.5, 0.8, 0.9, 0.95)]
        rows.append(f"{cons} & " + " & ".join(cells) + f" & {100 * sub.loc[0.9].cov_step1:.1f} & {100 * sub.loc[0.9].cov_step30:.1f} & "
                    f"{sub.loc[0.9].traj_all:.2f}")
    at90 = d[d.level == 0.9].assign(rng=lambda x: 100 * (x.coverage_seed_max - x.coverage_seed_min))
    raw = at90.construction.str.contains("raw")
    r_cal, r_raw = at90[~raw].rng.max(), at90[raw].rng.max()
    who_cal = at90[~raw].sort_values("rng").iloc[-1].construction
    who_raw = at90[raw].sort_values("rng").iloc[-1].construction
    cap = ("\\textbf{Post hoc descriptive} breakdown of ID-test coverage (\\%) by nominal level, at the first and last forecast "
           "step (nominal 90\\%), and simultaneous whole-trajectory coverage (fraction of windows with all 30 steps and 5 channels "
           "inside the interval; no construction targets this quantity). Means over three training repeats. At 90\\%, the largest "
           f"range of coverage across repeats is {r_cal:.1f} percentage points among the split-conformal rows ({who_cal}) and "
           f"{r_raw:.1f} points among the uncalibrated Gaussian rows ({who_raw}); these are seed ranges, not recording-level intervals.")
    return tex_table(f"{out}/tab_o1.tex", cap, "tab:o1", "lccccccc",
                     "Construction & 50\\% & 80\\% & 90\\% & 95\\% & Step 1 & Step 30 & Trajectory", rows)


def fig_levels(out):
    levels = [0.5, 0.8, 0.9, 0.95]
    fig, axes = plt.subplots(2, 2, figsize=(11, 7.2), sharex=True, sharey=True)
    for j, sp in enumerate(("test", "ood_test")):
        for i, raw in enumerate((False, True)):
            ax = axes[i, j]
            ax.plot(levels, levels, "k:", lw=1)
            for m, lab, fam, bb in ROWS:
                if fam.endswith("raw") != raw or bb not in ("LSTM", "MLP"):
                    continue
                pat, meth, var = {
                    "AR": (EVAL_TAG.get(m), "conformal", "horizon_channel"),
                    "EN": ("*_ens_rep*", "ensemble", "horizon_channel"), "DN": ("*_mcd_rep*", "mc_dropout", "horizon_channel"),
                    "GN": ("*_gauss_rep*", "gaussian", "horizon_channel"), "ENraw": ("*_ens_rep*", "ensemble", "raw_gaussian"),
                    "DNraw": ("*_mcd_rep*", "mc_dropout", "raw_gaussian"), "GNraw": ("*_gauss_rep*", "gaussian", "raw_gaussian")}[fam]
                pat = pat.replace("*_", f"{bb.lower()}_", 1) if pat.startswith("*_") else pat
                covs = []
                for p in sorted(glob.glob(f"{METRICS}/{pat}.json")):
                    ivs = json.load(open(p))["intervals"]
                    covs.append([next(v["coverage"] for v in ivs if v["split"] == sp and v["method"] == meth
                                      and v["variant"] == var and abs(v["level"] - l) < 1e-9) for l in levels])
                covs = np.array(covs)
                ax.plot(levels, covs.mean(0), color=COLOR[fam], ls=LS[bb], marker="o", ms=3, lw=1.4, label=f"{lab}, {bb}")
                ax.fill_between(levels, covs.min(0), covs.max(0), color=COLOR[fam], alpha=0.15, lw=0)
            ax.set_title(("ID test" if sp == "test" else "OOD test (exploratory)") + (" — uncalibrated bands" if raw else " — split conformal"),
                         fontsize=9)
            ax.grid(alpha=0.3)
            if i == 1:
                ax.set_xlabel("Nominal level")
            if j == 0:
                ax.set_ylabel("Empirical marginal coverage")
    fig.tight_layout(rect=(0, 0, 0.78, 1))
    for i in range(2):
        h, lbl = axes[i, 0].get_legend_handles_labels()
        axes[i, 1].legend(h, lbl, fontsize=7.5, loc="center left", bbox_to_anchor=(1.03, 0.5), frameon=False)
    p = f"{out}/fig_coverage_levels.pdf"
    fig.savefig(p)
    plt.close(fig)
    return p


def fig_horizon(out):
    fig, axes = plt.subplots(2, 2, figsize=(9, 7.0), sharex=True)
    for j, sp in enumerate(("test", "ood_test")):
        for m, lab, fam, bb in ROWS:
            if fam.endswith("raw") or bb not in ("LSTM", "MLP"):
                continue
            pat, meth = {"AR": (EVAL_TAG.get(m), "conformal"), "EN": (f"{bb.lower()}_ens_rep*", "ensemble"),
                         "DN": (f"{bb.lower()}_mcd_rep*", "mc_dropout"), "GN": (f"{bb.lower()}_gauss_rep*", "gaussian")}[fam]
            cov, wid = [], []
            for p in sorted(glob.glob(f"{METRICS}/{pat}.json")):
                mj = json.load(open(p))
                scale = np.asarray(mj["provenance"]["scale_for_normalised_metrics"])
                v = next(x for x in mj["intervals"] if x["split"] == sp and x["method"] == meth and x["variant"] == "horizon_channel"
                         and abs(x["level"] - 0.9) < 1e-9)
                cov.append(v["coverage_horizon"])
                wid.append((np.asarray(v["width_horizon_channel"]) / scale).mean(1))
            t = np.arange(1, 31)
            axes[0, j].plot(t, np.mean(cov, 0), color=COLOR[fam], ls=LS[bb], lw=1.4, label=f"{lab}, {bb}")
            axes[1, j].plot(t, np.mean(wid, 0), color=COLOR[fam], ls=LS[bb], lw=1.4)
        axes[0, j].axhline(0.9, color="k", ls=":", lw=1)
        axes[0, j].set_title("ID test" if sp == "test" else "OOD test (exploratory)", fontsize=9)
        axes[1, j].set_xlabel("Forecast step (s)")
        for a in axes[:, j]:
            a.grid(alpha=0.3)
    axes[0, 0].set_ylabel("Marginal coverage at nominal 90%")
    axes[1, 0].set_ylabel("Normalised width")
    h, lbl = axes[0, 0].get_legend_handles_labels()
    fig.tight_layout(rect=(0, 0.08, 1, 1))
    fig.legend(h, lbl, fontsize=7.5, loc="lower center", ncol=4, frameon=False)
    p = f"{out}/fig_horizon.pdf"
    fig.savefig(p)
    plt.close(fig)
    return p


EXAMPLE_PANELS = [("lstm_single_rep0", "conformal", "AR-SCP (single LSTM)"),
                  ("lstm_ens_rep0", "spread", "EN-SCP (LSTM ensemble)"),
                  ("lstm_mcd_rep0", "spread", "DN-SCP (LSTM, MC dropout)"),
                  ("lstm_gauss_rep0", "spread", "GN-SCP (Gaussian LSTM)")]
CH_LABEL = {"u": "$u$ (m/s)", "v": "$v$ (m/s)", "p": "$p$ (rad/s)", "r": "$r$ (rad/s)", "phi": "$\\phi$ (rad)"}


def fig_example(out, eval_root, data_base="data/processed/darus", expected=None):
    """Presentation-only regeneration of the frozen example-window figure (same rule, same data)."""
    from src.analysis.rebuild import EvalDir
    ref = EvalDir(os.path.join(eval_root, EXAMPLE_PANELS[0][0]))
    wid = frozen.select_example_window(ref, "test")
    if expected is not None and wid != expected["window_id"]:
        raise RuntimeError(f"example window {wid} differs from the frozen selection {expected['window_id']}")
    win = ref.windows("test").iloc[wid]
    rec = pd.read_csv(os.path.join(data_base, "patrol_ship_routine/test", win.recording))
    start = int(win.start_row)
    fig, axes = plt.subplots(len(CH), len(EXAMPLE_PANELS), figsize=(12, 10), sharex=True, sharey="row", squeeze=False)
    for j, (tag, kind, label) in enumerate(EXAMPLE_PANELS):
        ed = EvalDir(os.path.join(eval_root, tag))
        if not ed.windows("test").equals(ref.windows("test")):
            raise ValueError(f"{tag}: windows differ from the reference evaluation")
        iv = ed.interval("test", kind, "horizon_channel", 0.9)
        a = ed.arrays("test")
        t = np.arange(1, a["y"].shape[1] + 1)
        for i, ch in enumerate(CH):
            ax = axes[i, j]
            ax.plot(np.arange(-29, 1), rec[ch].to_numpy()[start:start + 30], color="0.45", lw=1.1, label="history")
            ax.fill_between(t, iv.lower[wid, :, i], iv.upper[wid, :, i], color=COLOR[{"conformal": "AR"}.get(kind, {"lstm_ens_rep0": "EN", "lstm_mcd_rep0": "DN", "lstm_gauss_rep0": "GN"}.get(tag))],
                            alpha=0.25, lw=0, label="90% interval")
            ax.plot(t, a["y"][wid, :, i], "k--", lw=1.1, label="observed")
            ax.plot(t, a["mean"][wid, :, i], color="C0", lw=1.3, label="prediction")
            ax.axvline(0.5, color="0.7", lw=0.8)
            ax.tick_params(labelsize=10)
            ax.grid(alpha=0.25)
            if j == 0:
                ax.set_ylabel(CH_LABEL[ch], fontsize=12)
            if i == 0:
                ax.set_title(label, fontsize=12)
            if i == len(CH) - 1:
                ax.set_xlabel("Time from forecast origin (s)", fontsize=11)
    h, lbl = axes[0, 0].get_legend_handles_labels()
    fig.tight_layout(rect=(0, 0.05, 1, 0.97))
    fig.legend(h, lbl, loc="lower center", ncol=4, fontsize=11, frameon=False)
    fig.suptitle(f"ID test window {wid} (recording {win.recording.replace('.csv', '')}, start row {start}): "
                 "90% split-conformal intervals", fontsize=12)
    path = f"{out}/fig_example_window.pdf"
    fig.savefig(path)
    plt.close(fig)
    return path, {"window_id": wid, "recording": win.recording, "start_row": start}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="experiments/analysis/v3/report_pub")
    ap.add_argument("--example_pdf", default="experiments/analysis/v3/report/figures/example_window.pdf",
                    help="frozen example-window figure; copied only if --eval_root predictions are unavailable")
    ap.add_argument("--eval_root", default="experiments/eval/v3",
                    help="evaluation dirs with saved predictions (cluster copy) for regenerating the example figure")
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)
    S = summaries()
    outs = [table_roles(args.out), table_baselines(S, args.out), table_channels_rmse(S, args.out),
            table_uq(S, args.out, "test", "tab_uq_id"), table_uq(S, args.out, "ood_test", "tab_uq_ood"),
            table_paired(args.out), table_matched_posthoc(args.out), table_channel_coverage(S, args.out),
            table_o1(args.out), prose_values(S, args.out), fig_levels(args.out), fig_horizon(args.out)]
    ex_meta = json.load(open("experiments/analysis/v3/report/analysis_manifest.json"))["example_window"]
    have_preds = all(os.path.exists(os.path.join(args.eval_root, t, "predictions_test.npz")) for t, _, _ in EXAMPLE_PANELS)
    if have_preds:
        ex, regenerated = fig_example(args.out, args.eval_root, expected=ex_meta)
        ex_source = "regenerated from saved predictions (presentation only; same rule and window)"
    else:
        ex = f"{args.out}/fig_example_window.pdf"
        with open(args.example_pdf, "rb") as src, open(ex, "wb") as dst:
            dst.write(src.read())
        ex_source = f"FROZEN COPY of {args.example_pdf} (predictions unavailable locally; labels not yet updated)"
    outs.append(ex)
    inputs = sorted(glob.glob(f"{BOOT}/*.csv") + glob.glob(f"{METRICS}/*.json") + glob.glob(f"{POSTHOC}/*.csv")
                    + [args.example_pdf] + glob.glob("experiments/configs/v3/*.yaml"))
    json.dump({"generator": "src.analysis.report_pub", "inputs": {p: sha(p) for p in inputs},
               "outputs": {p: sha(p) for p in outs}, "example_window": ex_meta, "example_figure_source": ex_source,
               "deviation": "D-P1 presentation-only changes (see REVISION_TRACKER.md)"},
              open(f"{args.out}/manifest.json", "w"), indent=1)
    print(f"wrote {len(outs)} outputs to {args.out}")


if __name__ == "__main__":
    main()
